import { useMemo, useState } from 'react'

const ROLE_FOCUS={
 remote_sensing_coordinator:'Ensure unresolved oversight concerns are elevated and do not enter the approved regional plan without a documented coordination path.',
 remote_sensing_manager:'Execute only authorized portions of missions and notify the Coordinator when an oversight concern affects timing or mission value.',
 collection_manager:'Clarify purpose, narrow collection, document the issue, and seek the appropriate oversight or legal review.',
 upad_lno:'Protect processing, assessment, dissemination, and releasability boundaries while reporting production impact through the RS Manager.',
}
const ACTIONS=['Clarify mission purpose','Narrow collection area or scope','Modify dissemination','Pause affected activity','Continue authorized portions','Seek oversight / legal guidance','Document and elevate concern']

export default function IntelligenceOversight({role,missionState,onUpdateCase,onAddCase}){
 const [selectedId,setSelectedId]=useState(missionState.oversight.cases[0]?.id)
 const [newTitle,setNewTitle]=useState('')
 const [newConcern,setNewConcern]=useState('')
 const selected=useMemo(()=>missionState.oversight.cases.find(c=>c.id===selectedId)||missionState.oversight.cases[0],[missionState,selectedId])
 const editable=role==='collection_manager'
 const canCoordinate=role==='remote_sensing_coordinator'||role==='collection_manager'
 if(!selected) return null
 return <div className="oversight-workspace">
  <section className="panel oversight-hero"><div><span className="eyebrow">Step 4F · Intelligence Oversight Workflow</span><h2>Identify, Clarify, Document, and Elevate</h2><p>NEXUS RS surfaces potential concerns without inventing legal conclusions. The trainee must preserve mission purpose, use the least intrusive authorized approach, and follow the proper coordination path.</p></div><div className="oversight-role-focus"><span>ROLE EMPHASIS</span><strong>{ROLE_FOCUS[role]}</strong></div></section>
  <aside className="panel oversight-queue"><div className="panel-heading"><h3>Oversight Cases</h3><span className="chip amber">{missionState.oversight.cases.filter(c=>c.status!=='resolved').length} OPEN</span></div><div className="oversight-case-list">{missionState.oversight.cases.map(c=><button key={c.id} className={selected.id===c.id?'selected':''} onClick={()=>setSelectedId(c.id)}><div><strong>{c.id}</strong><span className={`oversight-status ${c.status}`}>{c.status}</span></div><p>{c.title}</p><small>{c.requirementId} · {c.owner}</small></button>)}</div></aside>
  <section className="panel oversight-detail"><div className="panel-heading"><h3>{selected.title}</h3><span className={`chip ${selected.severity==='high'?'red':'amber'}`}>{selected.severity.toUpperCase()}</span></div><div className="oversight-detail-grid"><div><span>Requirement</span><strong>{selected.requirementId}</strong></div><div><span>Owner</span><strong>{selected.owner}</strong></div><div><span>Decision Deadline</span><strong>{selected.deadline}</strong></div><div><span>Status</span><strong>{selected.status}</strong></div><div className="wide"><span>Potential Concern</span><strong>{selected.concern}</strong></div><div className="wide"><span>Known Facts</span><strong>{selected.knownFacts}</strong></div><div className="wide"><span>Uncertainty</span><strong>{selected.uncertainty}</strong></div></div><label>Coordination / Resolution Note<textarea disabled={!canCoordinate} value={selected.resolutionNote||''} onChange={e=>onUpdateCase(selected.id,{resolutionNote:e.target.value})}/></label><div className="oversight-actions"><select disabled={!editable} value={selected.selectedAction||''} onChange={e=>onUpdateCase(selected.id,{selectedAction:e.target.value,status:'coordinating'})}><option value="">Select action</option>{ACTIONS.map(a=><option key={a}>{a}</option>)}</select><button className="ghost-button" disabled={!canCoordinate} onClick={()=>onUpdateCase(selected.id,{status:'elevated'})}>Elevate</button><button className="primary-button small" disabled={!canCoordinate||!selected.resolutionNote?.trim()} onClick={()=>onUpdateCase(selected.id,{status:'resolved',resolvedAt:'CURRENT LOCAL'})}>Resolve / Document</button></div><p className="oversight-warning">NEXUS does not determine legality. It records the concern, requires clarification, and routes the issue to the proper authority.</p></section>
  <section className="panel oversight-new"><div className="panel-heading"><h3>Flag New Concern</h3><span className="chip slate">COLLECTION MANAGER</span></div><div className="oversight-new-grid"><input disabled={!editable} value={newTitle} onChange={e=>setNewTitle(e.target.value)} placeholder="Short title"/><textarea disabled={!editable} value={newConcern} onChange={e=>setNewConcern(e.target.value)} placeholder="Describe the potential concern and what is uncertain."/><button className="primary-button small" disabled={!editable||!newTitle.trim()||!newConcern.trim()} onClick={()=>{onAddCase({title:newTitle,concern:newConcern});setNewTitle('');setNewConcern('')}}>Add Oversight Case</button></div></section>
  <section className="panel oversight-doctrine"><div className="panel-heading"><h3>Permitted Training Responses</h3><span className="chip teal">NO AUTOMATIC CANCELLATION</span></div><div className="oversight-action-grid">{ACTIONS.map(a=><div key={a}><strong>{a}</strong><p>The correct choice depends on mission purpose, authority, scope, current facts, and available guidance.</p></div>)}</div></section>
 </div>
}
